### ISSUE TITLE
[Bug] Safari 브라우저에서 접근 시 에러

### ISSUE THREAD

**Issue by brixxt27** [5GoInMul-Transcendence/ft_transcendence#41]
## Description
```
[4:14:59 PM] File change detected. Starting incremental compilation...

[4:14:59 PM] Found 0 errors. Watching for file changes.

Debugger listening on ws://127.0.0.1:9229/68f1898c-041f-4af1-bcfc-b7f69bb021d3
For help, see: https://nodejs.org/en/docs/inspector
[Nest] 91969  - 08/09/2023, 4:14:59 PM     LOG [NestFactory] Starting Nest application...
[Nest] 91969  - 08/09/2023, 4:15:00 PM     LOG [InstanceLoader] SessionModule dependencies initialized +27ms
[Nest] 91969  - 08/09/2023, 4:15:00 PM     LOG [InstanceLoader] TypeOrmModule dependencies initialized +0ms
[Nest] 91969  - 08/09/2023, 4:15:00 PM     LOG [InstanceLoader] ConfigHostModule dependencies initialized +0ms
[Nest] 91969  - 08/09/2023, 4:15:00 PM     LOG [InstanceLoader] ConfigModule dependencies initialized +0ms
[Nest] 91969  - 08/09/2023, 4:15:00 PM     LOG [InstanceLoader] ConfigModule dependencies initialized +0ms
[Nest] 91969  - 08/09/2023, 4:15:00 PM     LOG [InstanceLoader] AppModule dependencies initialized +2ms
[Nest] 91969  - 08/09/2023, 4:15:00 PM     LOG [InstanceLoader] TypeOrmCoreModule dependencies initialized +71ms
[Nest] 91969  - 08/09/2023, 4:15:00 PM     LOG [InstanceLoader] TypeOrmModule dependencies initialized +0ms
[Nest] 91969  - 08/09/2023, 4:15:00 PM     LOG [InstanceLoader] UserModule dependencies initialized +1ms
[Nest] 91969  - 08/09/2023, 4:15:00 PM     LOG [InstanceLoader] SignupModule dependencies initialized +0ms
[Nest] 91969  - 08/09/2023, 4:15:00 PM     LOG [InstanceLoader] LoginModule dependencies initialized +0ms
[Nest] 91969  - 08/09/2023, 4:15:00 PM     LOG [RoutesResolver] AppController {/}: +9ms
[Nest] 91969  - 08/09/2023, 4:15:00 PM     LOG [RouterExplorer] Mapped {/, GET} route +1ms
[Nest] 91969  - 08/09/2023, 4:15:00 PM     LOG [RoutesResolver] LoginController {/login}: +0ms
[Nest] 91969  - 08/09/2023, 4:15:00 PM     LOG [RouterExplorer] Mapped {/login/oauth/42, GET} route +0ms
[Nest] 91969  - 08/09/2023, 4:15:00 PM     LOG [RouterExplorer] Mapped {/login/oauth/42/redirect, GET} route +1ms
[Nest] 91969  - 08/09/2023, 4:15:00 PM     LOG [RoutesResolver] SignupController {/signup}: +0ms
[Nest] 91969  - 08/09/2023, 4:15:00 PM     LOG [RouterExplorer] Mapped {/signup, POST} route +0ms
[Nest] 91969  - 08/09/2023, 4:15:00 PM     LOG [NestApplication] Nest application successfully started +1ms
[Nest] 91969  - 08/09/2023, 4:15:07 PM   ERROR [ExceptionsHandler] The provided authorization grant is invalid, expired, revoked, does not match the redirection URI used in the authorization request, or was issued to another client.
TokenError: The provided authorization grant is invalid, expired, revoked, does not match the redirection URI used in the authorization request, or was issued to another client.
    at FtStrategy.OAuth2Strategy.parseErrorResponse (/Users/jayoon/code/ft_transcendence/back/web-app/node_modules/passport-oauth2/lib/strategy.js:373:12)
    at FtStrategy.OAuth2Strategy._createOAuthError (/Users/jayoon/code/ft_transcendence/back/web-app/node_modules/passport-oauth2/lib/strategy.js:420:16)
    at /Users/jayoon/code/ft_transcendence/back/web-app/node_modules/passport-oauth2/lib/strategy.js:177:45
    at /Users/jayoon/code/ft_transcendence/back/web-app/node_modules/oauth/lib/oauth2.js:191:18
    at passBackControl (/Users/jayoon/code/ft_transcendence/back/web-app/node_modules/oauth/lib/oauth2.js:132:9)
    at IncomingMessage.<anonymous> (/Users/jayoon/code/ft_transcendence/back/web-app/node_modules/oauth/lib/oauth2.js:157:7)
    at IncomingMessage.emit (node:events:523:35)
    at endReadableNT (node:internal/streams/readable:1367:12)
    at processTicksAndRejections (node:internal/process/task_queues:82:21)
```
## To do
- [ ] 에러 사항 확인하기

**Comment by brixxt27** [comment]
42서버 에러로 500번 대 응답을 받았다. 때문에 우리가 신경 쓸 게 아니다.
