### ISSUE TITLE
[Feat] Interceptor 및 exception filter 에서 API 응답 형식에 맞춰 가공하기

### ISSUE THREAD

**Issue by brixxt27** [5GoInMul-Transcendence/ft_transcendence#47]
## Description
-  Interceptor(성공0000, 리다이렉트0002) 및 exception(실패0001, 메시지 포함) filter 에서 API 응답 형식에 맞춰 가공하기
- 리다이렉션으로 들어오는 모든 응답은 200으로 바꿔주고, statusCode 는 0002 로 변경해줘야 한다.
- 301은 영구적으로 브라우저 측에서 변경해버리니 302를 사용해야 한다.
## To do
- [ ]

**Comment by brixxt27** [comment]
# HTTP response status code
## 200 OK
## 301 Moved Permanently
- 하이퍼텍스트 전송 프로토콜(HTTP) 301 영구적으로 리디렉션됨 상태 응답 코드는 요청된 리소스가 위치 헤더에 지정된 URL로 최종적으로 이동되었음을 나타냅니다. 브라우저는 새 URL로 리디렉션되고 검색 엔진은 리소스에 대한 링크를 업데이트합니다.
## 302 Found
- HTTP method 및 body 를 변경할 수 있다.
## 303 See other
- 리다이렉션이 요청된 리소스에 직접 접근하지 않고, 다른 페이지로 리다이렉션 되었다는 것을 나타낸다.
- 이 상태 코드는 클라이언트에게 리다이렉션을 나타냅니다.
- 클라이언트의 요청을 받은 서버는 요청한 리소스가 다른 URL에 위치하고 있음을 알려줍니다.
- 하지만, 클라이언트가 새로운 요청을 보낼 때에는 반드시 GET 메서드를 사용해야 합니다.
- 주로 POST 요청을 처리한 후에, 클라이언트가 결과 리소스를 GET으로 얻어야 할 때 사용됩니다.
## 307 Temporary redirect
- 302 와 동일하지만, HTTP Method 와 Body 를 변경할 수 없다는 것이 보장 되어 있다.
- GET 을 제외한 모든 리다이렉트는 이 307 을 추천 받는다.
- 일부 구현 클라이언트는 HTTP Method 를 의도치 않게 GET 으로 변경하는 경우가 있는다. 이 때 307 은 동작을 보장할 수 있지만, 302는 그렇지 못한다.
## 400 Bad
- HTTP(하이퍼텍스트 전송 프로토콜) 400 잘못된 요청 응답 상태 코드는 클라이언트 오류로 인식되는 문제(예: 잘못된 요청 구문, 잘못된 요청 메시지 프레이밍 또는 잘못된 요청 라우팅)로 인해 서버가 요청을 처리할 수 없거나 처리하지 않음을 나타냅니다.

**Comment by brixxt27** [comment]
```
    response
      // .status(status)
      .json(ApiResponseForm.bad(message));
```
위와 같은 형식으로 exception 객체의 status 에 가져온 status 를 넣었는데 이미 이 값으로 저장 되어 있는 것을 다시 바꾸려 하는 행위라 의미 없음. 그래서 지웠다.

**Comment by brixxt27** [comment]
# HttpExceptionFilter catch 메소드
### exception: HttpException 객체에 있는 데이터
```
HttpException: 현재 페이지가 없습니다!
    at AppService.getHello (/Users/jayoon/code/ft_transcendence/back/web-app/src/app.service.ts:6:11)
    at AppController.getHello (/Users/jayoon/code/ft_transcendence/back/web-app/src/app.controller.ts:10:28)
    at /Users/jayoon/code/ft_transcendence/back/web-app/node_modules/@nestjs/core/router/router-execution-context.js:38:29
    at InterceptorsConsumer.transformDeferred (/Users/jayoon/code/ft_transcendence/back/web-app/node_modules/@nestjs/core/interceptors/interceptors-consumer.js:31:33)
    at /Users/jayoon/code/ft_transcendence/back/web-app/node_modules/@nestjs/core/interceptors/interceptors-consumer.js:18:86
    at AsyncResource.runInAsyncScope (node:async_hooks:206:9)
    at bound (node:async_hooks:238:16)
    at Observable._subscribe (/Users/jayoon/code/ft_transcendence/back/web-app/node_modules/rxjs/src/internal/observable/defer.ts:55:15)
    at Observable._trySubscribe (/Users/jayoon/code/ft_transcendence/back/web-app/node_modules/rxjs/src/internal/Observable.ts:244:19)
    at /Users/jayoon/code/ft_transcendence/back/web-app/node_modules/rxjs/src/internal/Observable.ts:234:18 {
  response: '현재 페이지가 없습니다!',
  status: 200,
  options: undefined
}
```
### host 객체에 들어있는 데이터
```
ExecutionContextHost {
  args: [
    IncomingMessage {
      _readableState: [ReadableState],
      _events: [Object: null prototype] {},
      _eventsCount: 0,
      _maxListeners: undefined,
      socket: [Socket],
      httpVersionMajor: 1,
      httpVersionMinor: 1,
      httpVersion: '1.1',
      complete: true,
      rawHeaders: [Array],
      rawTrailers: [],
      joinDuplicateHeaders: undefined,
      aborted: false,
      upgrade: false,
      url: '/',
      method: 'GET',
      statusCode: null,
      statusMessage: null,
      client: [Socket],
      _consuming: false,
      _dumped: false,
      next: [Function: next],
      baseUrl: '',
      originalUrl: '/',
      _parsedUrl: [Url],
      params: {},
      query: {},
      res: [ServerResponse],
      body: {},
      _parsedOriginalUrl: [Url],
      sessionStore: [MemoryStore],
      sessionID: 'UOdu02gpEStqbX__4D9jgOdjLzse4jse',
      session: [Session],
      route: [Route],
      [Symbol(kCapture)]: false,
      [Symbol(kHeaders)]: [Object],
      [Symbol(kHeadersCount)]: 32,
      [Symbol(kTrailers)]: null,
      [Symbol(kTrailersCount)]: 0
    },
    ServerResponse {
      _events: [Object: null prototype],
      _eventsCount: 1,
      _maxListeners: undefined,
      outputData: [],
      outputSize: 0,
      writable: true,
      destroyed: false,
      _last: false,
      chunkedEncoding: false,
      shouldKeepAlive: true,
      maxRequestsOnConnectionReached: false,
      _defaultKeepAlive: true,
      useChunkedEncodingByDefault: true,
      sendDate: true,
      _removedConnection: false,
      _removedContLen: false,
      _removedTE: false,
      strictContentLength: false,
      _contentLength: null,
      _hasBody: true,
      _trailer: '',
      finished: false,
      _headerSent: false,
      _closed: false,
      socket: [Socket],
      _header: null,
      _keepAliveTimeout: 5000,
      _onPendingData: [Function: bound updateOutgoingData],
      req: [IncomingMessage],
      _sent100: false,
      _expect_continue: false,
      _maxRequestsPerSocket: 0,
      locals: [Object: null prototype] {},
      writeHead: [Function: writeHead],
      end: [Function: end],
      statusCode: 200,
      [Symbol(kCapture)]: false,
      [Symbol(kBytesWritten)]: 0,
      [Symbol(kNeedDrain)]: false,
      [Symbol(corked)]: 0,
      [Symbol(kOutHeaders)]: [Object: null prototype],
      [Symbol(errored)]: null,
      [Symbol(kHighWaterMark)]: 16384,
      [Symbol(kRejectNonStandardBodyWrites)]: false,
      [Symbol(kUniqueHeaders)]: null
    },
    [Function: next]
  ],
  constructorRef: null,
  handler: null,
  contextType: 'http',
  getRequest: [Function: getRequest],
  getResponse: [Function: getResponse],
  getNext: [Function: getNext]
}
```
